name: Test yaml
on: push
jobs:
  run-test-job:
    name: Test job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7.7'
      - run: pip install requests
        name: Install dependency
      - run: echo hello #python -m unittest test_jira_to_fakturoid-import.py
        name: Run tests
  push-docker-image:
    needs: run-test-job
    name: Push docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: sarkajana/fakturoid:latest
  run-dockerimage-on-server:
    needs: push-docker-image
    runs-on: ubuntu-latest
    steps:
      - name: Log in to server
        env:
          PASSWORD: ${{ secrets.SERVER_PASSWORD }}
          IP_ADDRESS: ${{ secrets.SERVER_IP }}
        run: |
          sudo apt-get install -y sshpass
          sshpass -p $PASSWORD ssh -o StrictHostKeyChecking=no root@$IP_ADDRESS
          apk add docker
          service docker start
          docker pull sarkajana/fakturoid:latest
          docker run sarkajana/fakturoid:latest

